gralloc/utils: dont error on unused parameters/variables
errors:
hardware/qcom-caf/sm8450/display/sdm/include/core/display_interface.h:474:63: error: unused parameter 'event_data' [-Werror,-Wunused-parameter]
  virtual DisplayError HandleQsyncState(const QsyncEventData &event_data) { return kErrorNone; }
                                                              ^
hardware/qcom-caf/sm8450/display/sdm/include/core/display_interface.h:477:56: error: unused parameter 'fps' [-Werror,-Wunused-parameter]
  virtual DisplayError NotifyFpsMitigation(const float fps, DisplayConcurrencyType concurrency,
                                                       ^
hardware/qcom-caf/sm8450/display/sdm/include/core/display_interface.h:477:84: error: unused parameter 'concurrency' [-Werror,-Wunused-parameter]
  virtual DisplayError NotifyFpsMitigation(const float fps, DisplayConcurrencyType concurrency,
                                                                                   ^
hardware/qcom-caf/sm8450/display/sdm/include/core/display_interface.h:478:49: error: unused parameter 'concurrency_begin' [-Werror,-Wunused-parameter]
                                           bool concurrency_begin) {

and

hardware/qcom-caf/sm8450/display/gralloc/QtiGralloc.cpp:188:14: error: unused variable 'p' [-Werror,-Wunused-variable]
  qti_ycbcr *p = reinterpret_cast<qti_ycbcr *>(in.data());

Signed-off-by: Nishant Kumar <www.rajsonu13@gmail.com>